
CREATE TABLE MY_FAVORITE_BOOKS (id INTEGER PRIMARY KEY, name TEXT, rating INTEGER );

INSERT INTO MY_FAVORITE_BOOKS VALUES (1, "diary_of_a_wimpy_kid", 4);

INSERT INTO MY_FAVORITE_BOOKS VALUES (2, "captain_underpants", 1);

INSERT INTO MY_FAVORITE_BOOKS VALUES (3, "99+ more", 2);
SELECT * FROM MY_FAVORITE_BOOKS;


